### ISSUE TITLE
Add a function to request a refreshtoken using auth flow

### ISSUE THREAD

**Issue by ili101** [ili101/PartnerCustomerCommunity#1]
This Issue is now for RefreshToken generation

(Original post moved to https://github.com/ili101/PartnerCustomerCommunity/issues/3)

**Comment by koenhalfwerk** [comment]
What is your fix at the moment? I've been looking at 
( the .NET samples)[https://github.com/microsoft/Partner-Center-DotNet-Samples/blob/master/sdk/SdkSamples/Configuration/UserAuthenticationSection.cs]

and I can see the new-module requires a Refreshtoken without generating one

**Comment by koenhalfwerk** [comment]
Im now trying to get this to work
https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model#get-authorization-code
followed hopefully by 
https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model#get-refresh-token

**Comment by ili101** [comment]
So let's list the stages from the doc and see what we have

1. Create a web app
2. Get an authorization code
3. Get a refresh token
4. Get an access token
5. Make a Partner Center API call

Stages 1-3
Workaround: I correctly use [this](https://www.cyberdrain.com/connect-to-exchange-online-automated-when-mfa-is-enabled-using-the-secureapp-model/)
Solution: Rewrite it without the deprecated modules, didn't look into it yest.
So if it's sending the token to https://localhost:44395/ in some stages we need a web server on this port, you can probably use [Pode](https://badgerati.github.io/Pode/) to retrieve it.

Stages 4
Solved: `New-PartnerAccessToken` is in this module

Stages 4 "Refresh"
Workaround: I don't know how to refresh it with the Dlls implementation, I didn't acutely need it as all my scrips run under 1 hour, and if I'm working on the terminal for long tine I just run `Connect-PartnerCenter` again.
Solution: This is the problem I created this Issue for, if you and I don't know how to solve it maybe I will post in the Powershell Repo/Discord for help?

**Comment by koenhalfwerk** [comment]
Thank you for the very clear summation, I think I have some ideas on problem 4, but I need to fix number 2 first.
I'll look into both options

The Powershell Discord should be an excellent start yes

**Comment by ili101** [comment]
I looked at the code from the PartnerCustomer model, they don't actually use the replyUrlsWithType, they hardcode localhost and find a free port. I copped the code from there.

@koenhalfwerk dose everything work for you? If so do you want to clean, pack it up and PR?
Also see if you have idea on how to solve problem 4. thank you!
```pwsh
$Port = 8399;
while (++$port -lt 9000) {
    try {
        Start-PodeServer {
            Add-PodeEndpoint -Address localhost -Port $Port -Protocol Http
            Add-PodeRoute -Method POST -Path '/' -ScriptBlock {
                Write-PodeJsonResponse -Value $WebEvent.Data 
            }
            # Close-PodeServer
        }
        break
    }
    catch {
        if ($_.Exception.Message -like '*Only one usage of each socket address*') {
            Write-Warning "Port $Port is taken with exception '$($_.Exception.Message)'; trying to connect to the next port."
        }
        else {
            throw $_
        }
    }
}

$Uri = 'https://login.microsoftonline.com/common/oauth2/authorize'
$Parameters = @{
    client_id     = $ApplicationCredential.UserName
    response_mode = 'form_post'
    response_type = 'code id_token'
    scope         = 'openid profile'
    nonce         = 1
    redirect_uri  = "http://localhost:$port/"
}
```

**Comment by koenhalfwerk** [comment]
Neat idea with the ports, and does explain why my dual port with get and post  was breaking.

Does it actually return the code or does it still require a copy/pasta? 

I'll combine what I can and make a pr

**Comment by ili101** [comment]
Not sure how to do that but we can do something like saving the token encrypted to Temp folder, then `Close-PodeServer`:
```pwsh
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port $Port -Protocol Http
    Add-PodeRoute -Method POST -Path '/' -ScriptBlock {
        Write-PodeJsonResponse -Value $WebEvent.Data
        $WebEvent.Data.code | ConvertTo-SecureString -AsPlainText | ConvertFrom-SecureString | Set-Content -Path (Join-Path $env:TEMP 'Token.txt')
        Close-PodeServer
    }
}
$token = Get-Content -Path (Join-Path $env:TEMP 'Token.txt') | ConvertTo-SecureString | ConvertFrom-SecureString -AsPlainText
Remove-Item (Join-Path $env:TEMP 'Token.txt')
```

@Badgerati can we return token string from `$WebEvent.Data.code` to the parent PS session without going to disc?

**Comment by koenhalfwerk** [comment]
> @koenhalfwerk dose everything work for you? If so do you want to clean, pack it up and PR? Also see if you have idea on how to solve problem 4. thank you!


quick regard to step 4, the refreshtoken inside new-partneraccesstoken's   $ReturnCred.refresh_token does not work for you? because it does for me.
I really need  to start the weekend, but ill come back to this on Monday, as well as extending new-partneraccesstoken with ```-Resource https://management.azure.com/```

**Comment by Badgerati** [comment]
Hey @ili101,

Yes, it's possible via [`Out-PodeVariable`](https://badgerati.github.io/Pode/Tutorials/Misc/Outputs/#variables) :)

```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port $Port -Protocol Http

    Add-PodeRoute -Method POST -Path '/' -ScriptBlock {
        Write-PodeJsonResponse -Value $WebEvent.Data
        Out-PodeVariable -Name Token -Value $WebEvent.Data.code
        Close-PodeServer
    }
}

# $Token is available here for use
```

**Comment by ili101** [comment]
`AuthenticationFlow -DeviceCode` done/merged.
`AuthenticationFlow -OIDC` with Pode to be done.

**Comment by ili101** [comment]
Dome using Pode in a Job https://github.com/ili101/PartnerCustomerCommunity/commit/9c47a1994a1ef84969cc9587d14363c788284a87#diff-78dfc795c2105c7b5e52de25a71230e2dcd0c0c232d84d2969c1c0b29ef58795R194-R266

## [0.0.2-alpha] - 2022-09-08
### Added
* `Connect-PartnerCenter -RefreshTokenScript`
* `New-PartnerWebApp -AuthenticationFlowAllowed`
* `New-PartnerRefreshToken -AuthenticationFlow OIDC` With [Pode](https://badgerati.github.io/Pode/)
